[project]
name = "pytheme"
version = "0.1.0"
description = "A Python theme manager"
readme = "README.md"
requires-python = ">=3.14.0b1"
dependencies = [
    "click>=8.2.0,<9.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
